[2025-01-07T13:30:02.950+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-07T13:30:02.963+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: projet_group.push scheduled__2025-01-07T13:20:00+00:00 [queued]>
[2025-01-07T13:30:02.968+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: projet_group.push scheduled__2025-01-07T13:20:00+00:00 [queued]>
[2025-01-07T13:30:02.968+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-01-07T13:30:02.976+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): push> on 2025-01-07 13:20:00+00:00
[2025-01-07T13:30:02.981+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1386) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-07T13:30:02.981+0000] {standard_task_runner.py:72} INFO - Started process 1389 to run task
[2025-01-07T13:30:02.982+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'projet_group', 'push', 'scheduled__2025-01-07T13:20:00+00:00', '--job-id', '61285', '--raw', '--subdir', 'DAGS_FOLDER/projet_group.py', '--cfg-path', '/tmp/tmpxxgq0fxx']
[2025-01-07T13:30:02.983+0000] {standard_task_runner.py:105} INFO - Job 61285: Subtask push
[2025-01-07T13:30:03.015+0000] {task_command.py:467} INFO - Running <TaskInstance: projet_group.push scheduled__2025-01-07T13:20:00+00:00 [running]> on host 5365fe4338c6
[2025-01-07T13:30:03.062+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='projet_group' AIRFLOW_CTX_TASK_ID='push' AIRFLOW_CTX_EXECUTION_DATE='2025-01-07T13:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-07T13:20:00+00:00'
[2025-01-07T13:30:03.062+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-07T13:30:03.063+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-07T13:30:03.063+0000] {logging_mixin.py:190} INFO - Current task name:push state:running start_date:2025-01-07 13:30:02.963407+00:00
[2025-01-07T13:30:03.063+0000] {logging_mixin.py:190} INFO - Dag name:projet_group and current dag run status:running
[2025-01-07T13:30:03.063+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-07T13:30:23.536+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/projet_group.py", line 103, in push_sql
    df = get_price()
         ^^^^^^^^^^^
  File "/opt/airflow/dags/projet_group.py", line 39, in get_price
    for curr in get_currency():
                ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/projet_group.py", line 22, in get_currency
    dico = [key for key in req_curr['market_data']['current_price'].keys()]
                           ~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'market_data'
[2025-01-07T13:30:23.543+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-07T13:30:23.543+0000] {logging_mixin.py:190} INFO - Task start:2025-01-07 13:30:02.963407+00:00 end:2025-01-07 13:30:23.542936+00:00 duration:20.579529
[2025-01-07T13:30:23.543+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): push> dag:<DAG: projet_group> dagrun:<DagRun projet_group @ 2025-01-07 13:20:00+00:00: scheduled__2025-01-07T13:20:00+00:00, state:running, queued_at: 2025-01-07 13:30:00.618071+00:00. externally triggered: False>
[2025-01-07T13:30:23.543+0000] {logging_mixin.py:190} INFO - Failure caused by 'market_data'
[2025-01-07T13:30:23.543+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=projet_group, task_id=push, run_id=scheduled__2025-01-07T13:20:00+00:00, execution_date=20250107T132000, start_date=20250107T133002, end_date=20250107T133023
[2025-01-07T13:30:23.551+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-07T13:30:23.552+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 61285 for task push ('market_data'; 1389)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/projet_group.py", line 103, in push_sql
    df = get_price()
         ^^^^^^^^^^^
  File "/opt/airflow/dags/projet_group.py", line 39, in get_price
    for curr in get_currency():
                ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/projet_group.py", line 22, in get_currency
    dico = [key for key in req_curr['market_data']['current_price'].keys()]
                           ~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'market_data'
[2025-01-07T13:30:23.559+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-07T13:30:23.568+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-07T13:30:23.569+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
