[2024-10-31T15:17:57.928+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-31T15:17:57.939+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Projet_poubelle.file_sensor manual__2024-10-31T15:17:54.335001+00:00 [queued]>
[2024-10-31T15:17:57.943+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Projet_poubelle.file_sensor manual__2024-10-31T15:17:54.335001+00:00 [queued]>
[2024-10-31T15:17:57.943+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-31T15:17:57.949+0000] {taskinstance.py:2888} INFO - Executing <Task(FileSensor): file_sensor> on 2024-10-31 15:17:54.335001+00:00
[2024-10-31T15:17:57.954+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=452) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-31T15:17:57.955+0000] {standard_task_runner.py:72} INFO - Started process 454 to run task
[2024-10-31T15:17:57.956+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Projet_poubelle', 'file_sensor', 'manual__2024-10-31T15:17:54.335001+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/Projet_poubelle.py', '--cfg-path', '/tmp/tmpu9sxwrzi']
[2024-10-31T15:17:57.956+0000] {standard_task_runner.py:105} INFO - Job 33: Subtask file_sensor
[2024-10-31T15:17:57.981+0000] {task_command.py:467} INFO - Running <TaskInstance: Projet_poubelle.file_sensor manual__2024-10-31T15:17:54.335001+00:00 [running]> on host 5365fe4338c6
[2024-10-31T15:17:58.020+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Projet_poubelle' AIRFLOW_CTX_TASK_ID='file_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-10-31T15:17:54.335001+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-31T15:17:54.335001+00:00'
[2024-10-31T15:17:58.020+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-31T15:17:58.021+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-31T15:17:58.021+0000] {logging_mixin.py:190} INFO - Current task name:file_sensor state:running start_date:2024-10-31 15:17:57.939807+00:00
[2024-10-31T15:17:58.021+0000] {logging_mixin.py:190} INFO - Dag name:Projet_poubelle and current dag run status:running
[2024-10-31T15:17:58.021+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-31T15:17:58.021+0000] {baseoperator.py:405} WARNING - FileSensor.execute cannot be called outside TaskInstance!
[2024-10-31T15:17:58.030+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/filesystem.py", line 123, in execute
    super().execute(context=context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 306, in execute
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 286, in execute
    poke_return = self.poke(context)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/filesystem.py", line 109, in poke
    self.log.info("Poking for file %s", self.path)
                                        ^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/filesystem.py", line 103, in path
    hook = FSHook(self.fs_conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/filesystem.py", line 64, in __init__
    conn = self.get_connection(fs_conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `fs_default` isn't defined
[2024-10-31T15:17:58.032+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-31T15:17:58.032+0000] {logging_mixin.py:190} INFO - Task start:2024-10-31 15:17:57.939807+00:00 end:2024-10-31 15:17:58.032199+00:00 duration:0.092392
[2024-10-31T15:17:58.032+0000] {logging_mixin.py:190} INFO - Task:<Task(FileSensor): file_sensor> dag:<DAG: Projet_poubelle> dagrun:<DagRun Projet_poubelle @ 2024-10-31 15:17:54.335001+00:00: manual__2024-10-31T15:17:54.335001+00:00, state:running, queued_at: 2024-10-31 15:17:54.343991+00:00. externally triggered: True>
[2024-10-31T15:17:58.032+0000] {logging_mixin.py:190} INFO - Failure caused by The conn_id `fs_default` isn't defined
[2024-10-31T15:17:58.032+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=Projet_poubelle, task_id=file_sensor, run_id=manual__2024-10-31T15:17:54.335001+00:00, execution_date=20241031T151754, start_date=20241031T151757, end_date=20241031T151758
[2024-10-31T15:17:58.039+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-31T15:17:58.039+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 33 for task file_sensor (The conn_id `fs_default` isn't defined; 454)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/filesystem.py", line 123, in execute
    super().execute(context=context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 306, in execute
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 286, in execute
    poke_return = self.poke(context)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/filesystem.py", line 109, in poke
    self.log.info("Poking for file %s", self.path)
                                        ^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/filesystem.py", line 103, in path
    hook = FSHook(self.fs_conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/filesystem.py", line 64, in __init__
    conn = self.get_connection(fs_conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `fs_default` isn't defined
[2024-10-31T15:17:58.048+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-31T15:17:58.057+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-31T15:17:58.058+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
