[2024-12-02T09:01:00.983+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-02T09:01:00.992+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: projet_groupe.push scheduled__2024-12-02T09:00:00+00:00 [queued]>
[2024-12-02T09:01:00.996+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: projet_groupe.push scheduled__2024-12-02T09:00:00+00:00 [queued]>
[2024-12-02T09:01:00.996+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-12-02T09:01:01.004+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): push> on 2024-12-02 09:00:00+00:00
[2024-12-02T09:01:01.010+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2241) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-02T09:01:01.011+0000] {standard_task_runner.py:72} INFO - Started process 2246 to run task
[2024-12-02T09:01:01.012+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'projet_groupe', 'push', 'scheduled__2024-12-02T09:00:00+00:00', '--job-id', '36308', '--raw', '--subdir', 'DAGS_FOLDER/projet.py', '--cfg-path', '/tmp/tmplww3j906']
[2024-12-02T09:01:01.013+0000] {standard_task_runner.py:105} INFO - Job 36308: Subtask push
[2024-12-02T09:01:01.041+0000] {task_command.py:467} INFO - Running <TaskInstance: projet_groupe.push scheduled__2024-12-02T09:00:00+00:00 [running]> on host 5365fe4338c6
[2024-12-02T09:01:01.091+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='projet_groupe' AIRFLOW_CTX_TASK_ID='push' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-02T09:00:00+00:00'
[2024-12-02T09:01:01.091+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-02T09:01:01.092+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-02T09:01:01.092+0000] {logging_mixin.py:190} INFO - Current task name:push state:running start_date:2024-12-02 09:01:00.992783+00:00
[2024-12-02T09:01:01.092+0000] {logging_mixin.py:190} INFO - Dag name:projet_groupe and current dag run status:running
[2024-12-02T09:01:01.092+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-02T09:01:01.166+0000] {logging_mixin.py:190} INFO - 429
[2024-12-02T09:01:01.167+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/projet.py", line 28, in data_db
    dico = [key for key in data['market_data']['current_price'].keys()]
                           ~~~~^^^^^^^^^^^^^^^
KeyError: 'market_data'
[2024-12-02T09:01:01.172+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-02T09:01:01.172+0000] {logging_mixin.py:190} INFO - Task start:2024-12-02 09:01:00.992783+00:00 end:2024-12-02 09:01:01.172328+00:00 duration:0.179545
[2024-12-02T09:01:01.173+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): push> dag:<DAG: projet_groupe> dagrun:<DagRun projet_groupe @ 2024-12-02 09:00:00+00:00: scheduled__2024-12-02T09:00:00+00:00, state:running, queued_at: 2024-12-02 09:01:00.160484+00:00. externally triggered: False>
[2024-12-02T09:01:01.173+0000] {logging_mixin.py:190} INFO - Failure caused by 'market_data'
[2024-12-02T09:01:01.173+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=projet_groupe, task_id=push, run_id=scheduled__2024-12-02T09:00:00+00:00, execution_date=20241202T090000, start_date=20241202T090100, end_date=20241202T090101
[2024-12-02T09:01:01.179+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-02T09:01:01.179+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 36308 for task push ('market_data'; 2246)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/projet.py", line 28, in data_db
    dico = [key for key in data['market_data']['current_price'].keys()]
                           ~~~~^^^^^^^^^^^^^^^
KeyError: 'market_data'
[2024-12-02T09:01:01.224+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-02T09:01:01.242+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-02T09:01:01.243+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
